version: '3.8'

networks:
  kafka-net:
    external: true

volumes:
  flink-checkpoints-directory:

services:
  jobmanager:
    image: flink:1.13.1-scala_2.11-java11
    hostname: jobmanager
    ports:
      - "8083:8083"
    command: "standalone-job"
    environment:
      JVM_ARGS: "-Dconfig.resource=application.development.conf"
    volumes:
      - ../build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints-directory
      - ../data/flink/savepoints:/tmp/flink-savepoints-directory
    networks:
      - kafka-net

  taskmanager-1:
    image: flink:1.13.1-scala_2.11-java11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      JVM_ARGS: "-Dconfig.resource=application.development.conf"
    volumes:
      - ../build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - ../data/flink/checkpoints:/tmp/flink-checkpoints-directory
      - ../data/flink/savepoints:/tmp/flink-savepoints-directory
    networks:
      - kafka-net